### ISSUE TITLE
Error with TW Essentials Bonus/Sets tab

### ISSUE THREAD

**Issue by BelleBernice** [TomRobert/TWIR#2]
![dE6jb4tlhB](https://github.com/user-attachments/assets/98db45cc-222d-4184-8851-db696cbfb8b5)

This error pops up when you click the "Bonus/Sets" or "WebCenter" tabs.

> TypeError: Cannot read properties of undefined (reading 'type') (ItemPopup.getXHTML :4145:64)

Plus, the link for the issues page is wrong. [This is what it says.](https://tomrobert.github.io/TWIR//issues)

**Comment by TomRobert** [comment]
And the issue in TW Essentials [is fixed](https://github.com/The-West-Scripts/The-West-Essentials/commit/1d5b9272aa47190b97161e5d63d6ec55220c336e) as well. Thank you.
